---
name: ci-builder

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'Dockerfile'
      - '.github/workflows/ci-docker.yml'
      - '.github/workflows/sonarcloud.yml'
      - '.github/workflows/codeql-analysis'

jobs:
  ci-builder:
    permissions:
      contents: read
      pull-requests: write
      packages: read
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/builder:${{ github.ref_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f
      - name: Configure
        run: make clean configure
      - name: Lint
        run: make lint
      - name: Build
        run: make build
#      - name: Test
#        run: make test
