---
name: ci-docker

on:
  push:
    branches:
      - 'main'
    paths:
      - 'docker.d/*'
      - '.github/workflows/ci-docker.yml'

jobs:
  ci-docker:
    permissions:
      contents: write
      packages: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull existing images (if any)
        run: |
          for df in docker.d/*.docker; do
            img=$(basename "$df" .docker)
            docker pull ghcr.io/${{ github.repository_owner }}/$img:${{ github.ref_name }} || true
          done

      - name: Build & push all Docker images
        run: |
          for df in docker.d/*.docker; do
            img=$(basename "$df" .docker)
            docker buildx build \
              --file "$df" \
              --tag ghcr.io/${{ github.repository_owner }}/$img:${{ github.ref_name }} \
              --push \
              .
          done

