---
# ci-docker.yml
# (c) 2025 Asymmetric Effort, LLC. <scaldwell@asymmetric-effort.com>
name: ci-docker

on:
  push:
    branches:
      - '**'
    paths:
      - 'Dockerfile'
      - '.github/workflows/ci-docker.yml'
      - '!tools/project-automation/project-automation.py'
jobs:
  ci-docker:
    permissions:
      contents: write
      packages: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull existing image (if any)
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/project_automation:${{ github.ref_name }} || true
          docker pull ghcr.io/${{ github.repository_owner }}/builder:${{ github.ref_name }} || true
      - name: Build and push Docker image (project_automation)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          target: project_automation
          tags: ghcr.io/${{ github.repository_owner }}/project_automation:${{ github.ref_name }}
      - name: Build and push Docker image (builder)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          target: project_automation
          tags: ghcr.io/${{ github.repository_owner }}/builder:${{ github.ref_name }}
