name: CI

on:
    push:
        branches: ['**']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f

            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y build-essential cmake

            - name: Build and Test
              run: make clean build test
