---
name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    permissions:
        contents: read
        pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f
      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update -y
          sudo apt-get install -y build-essential cmake ccache g++-13
      - name: Build and Test
        run: make clean configure lint build test
