---
name: CI

on:
  push:
    branches:
      - '**'

jobs:
  ci-pipeline:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f
      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          export DEBIAN_FRONTEND=noninteractive
          echo "USER: $(whoami), SHELL: ${SHELL}"
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update -y
          sudo apt-get install -y build-essential cmake ccache clang libc++-dev libc++abi-dev make cppcheck wget \
          wget https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
          chmod +x install.sh
          ./install.sh
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/runner/.bashrc
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install markdownlint-cli
          command -v markdownlint || exit 1
      - name: Configure
        run: make clean configure
      - name: Lint
        run: make lint
#      - name: Build
#        run: make build
#      - name: Test
#        run: make test
