# .github/workflows/project-automation.yml
# (c) 2025 Asymmetric Effort, LLC. <scaldwell@asymmetric-effort.com>
---
name: project-automation
on:
  push:
    branches:
      - 'main'
    paths:
      - 'PROJECT.yaml'
      - '.github/workflows/project-automation.yml'
permissions:
  contents: read
  packages: read
  repository-projects: write
jobs:
  manage_project:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/project_automation:${{ github.ref_name }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sync Project
        run: python3 /opt/project-automation.py
