# .github/workflows/project-automation.yml
# (c) 2025 Asymmetric Effort, LLC. <scaldwell@asymmetric-effort.com>
---
name: project-automation
on:
  push:
    branches:
      - 'main'
    paths:
      - 'PROJECT.yaml'
      - '.github/workflows/project-automation.yml'
      - 'tools/project-automation/project-automation.py'
      - 'tools/project-automation/requirements.txt'

permissions:
  checks: read
  contents: read
  discussions: write
  issues: write
  packages: read
  pages: write
  repository-projects: write
jobs:
  project-updater:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Prepare the environment
        run: |
          sudo apt-get update -y && \
          sudo apt-get install gh python3 python3-pip python3-venv
      - name: Create virtual environment
        run: |
          python3 -m venv venv && \
          source venv/bin/activate && \
      - name: Install Python dependencies
        run: |
          pip3 install -r tools/project-automation/requirements.txt
          pip3 freeze
      - name: Sync Project
        run: |
          echo "gh cli: $(which gh)"
          source venv/bin/activate && \
          python3 tools/project-automation/project-automation.py
