# .github/workflows/project-automation.yml
# (c) 2025 Asymmetric Effort, LLC. <scaldwell@asymmetric-effort.com>
---
name: project-automation

on:
  push:
    branches:
      - '**'
    paths:
      - 'Dockerfile'
      - '.github/workflows/ci-docker.yml'
      - '.github/workflows/sonarcloud.yml'
      - '.github/workflows/codeql-analysis'
      - '.github/workflows/project-automation.yml'

permissions:
  contents: read
  repository-projects: write

jobs:
  manage_project:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/project_automation:${{ github.ref_name }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      repository-projects: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sync Project
        run: python3 project-automation.py
