# .github/workflows/project-automation.yml
# (c) 2025 Asymmetric Effort, LLC. <scaldwell@asymmetric-effort.com>
---
name: project-automation
on:
  push:
    branches:
      - 'main'
    paths:
      - 'PROJECT.yaml'
      - '.github/workflows/project-automation.yml'
      - 'tools/project-automation/project-automation.py'

permissions:
  checks: read
  contents: read
  discussions: write
  issues: write
  packages: read
  pages: write
  repository-projects: write
jobs:
  project-updater:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update -y && \
          sudo apt-get upgrade -y && \
          sudo apt-get install gh python3 python3-pip python3-venv && \
          virtualenv venv && \
          source venv/bin/activate && \
          pip3 install -r tools/project-automation/requirements.txt
      - name: Sync Project
        run: |
          source venv/bin/activate && \
          python3 tools/project-automation/project-automation.py
